### ISSUE TITLE
Compatibility with D3 4.0+?

### ISSUE THREAD

**Issue by chrisalcantara** [fivethirtyeight/d3-pre#3]
Thank you for this awesome tool. 

I ran into an issue using this for a chart I'm making using D3 4.0 code. In the browser I'm getting this error message: `Uncaught TypeError: Cannot read property 'axis' of undefined`, which points to line 43 in browser.js: `d3.svg._axis = d3.svg.axis;`. 

The new API docs use `axisTop`, `axisLeft`, `axisRight` and `axisBottom`. Is there a workaround or does this tool strictly worth with D3 V3 code?

**Comment by mathisonian** [comment]
Thanks @chrisalcantara. Currently this is only tested against `v3`, but I plan to add support for `v4` shortly

**Comment by chrisalcantara** [comment]
Looking forward to it 👍

**Comment by mathisonian** [comment]
Hey @chrisalcantara, do you have handy example code for what is failing here? I have a branch that should be working with most `v4` changes but need to test on axes still

**Comment by chrisalcantara** [comment]
What exactly are you looking for? The line of the code that's giving me the error?

**Comment by mathisonian** [comment]
Was just looking for more test cases but I think it should be all sorted out. `v1.3.0` is released on npm and passes all tests with v4 of d3. Please let me know if you continue to have issues!

**Comment by chrisalcantara** [comment]
Thanks so much!
